# encoding: UTF-8

include ActionView::Helpers::TextHelper

data = ["Aby miłość trwała przez całe życie, trzeba ją pielegnować starannie jak ogród",
"Bitwa nie pokój, śmierć nie życie",
"Bogatym się staje, kto na swoim przestaje",
"Broda mądrości nie odda",
"Brudną bieliznę w domu prać trzeba",
"Chcesz się dowiedzieć prawdy o sobie, pokłóć się z przyjacielem",
"Chowaj grosinę na czarną godzinę",
"Chromy cierpliwy dalej zajdzie, niż zdrowy leniwy",
"Co dzień człowiek mędrszy",
"Co się odwlecze to nie uciecze",
"Co w głupcu nawet nie zważają, to w mędrcu za występki mają",
"Co zaszkodziło, to nauczyło",
"Czego nie umiesz odmówić, daj pierwej,, niż będą prosić",
"Często w grób lezie, kto przed nim ucieka",
"Człowiek człowiekowi zdrowie, żywot",
"Człowiek rozumny nie waha się zmienić zdanie",
"Człowiek się nie dla siebie rodzi, żyć mu też tytko sobie się nie godzi",
"Czym kto wojuje, od tego ginie",
"Dobre ludzkie rozumienie stoi za wyborne mienie",
"Dobrodziejstwa wyświadczonego nie wymawiaj",
"Dobrze przy jednym ogniu dwie pieczenie upiec",
"Do śmierci człowiek rozumu się uczy, a na starość głupim umiera",
"Dwa razy daje, kto prędko daje",
"Gdzie bywasz rzadziej, tam przyjmują rzadziej",
"Gdzie diabeł nie może, tam babę pośle",
"Gdzie kucharek sześć tam nie ma co jeść",
"Głupi, gdy milczy, za mądrego ujdzie",
"Gość przybyły na chwilę widzi wokoło na milę",
"Grosz oszczędzony może uróść w miliony",
"Honor nie szpeci godnego ani godny honoru",
"Honor jak papier, gdy raz się splami, już go nie wyczyścisz",
"I z nędzy można przyjść do pieniędzy",
"Im gość rzadszy, tym milszy",
"Jak cię widzą, tak cię piszą",
"Jaki pan, taki kram, jaki krój, taki strój",
"Jaki rycerz, taka szabla",
"Jakie częstowanie, takie dziękowanie",
"Jako się kto sprawuje, takie szczęście uczuje",
"Jeśli chcesz być kochany, kochaj sam",
"Jeśli chcesz być szanowanym, szanuj drugich",
"Językiem jak chcesz, ale ręką się strzeż",
"Język wynurzy, co się w sercu burzy",
"Każda rzecz dobra sama się zaleca",
"Każdemu życie mile",
"Każdy człek bliźni, ale swój najbliższy",
"Każdy człek chwali swój wiek",
"Każdy tym, co sam lubi, drugich częstuje",
"Każdy w młodości skory do miłości",
"Kiedy miłość szepce, rozum milczeć musi",
"Komu nałóg w naturę obraca, siodło mu łóżkiem, odpoczynkiem praca",
"Komu w drogę, temu czas",
"Krowa krowie mleka nie wypije",
"Krótki żywot na świecie, lecz długa nauka",
"Kto czuje przywarę, niechże gada w miarę",
"Kto dba, ten i ma; a kto nie dba, ten nic nie ma",
"Kto kupuje, czego mu nie potrzeba, nie będzie miał za co kupić chleba",
"Kto mieczem wojuje, od niego zginie",
"Kto milczy, znać, że przyzwała",
"Kto nikogo nie kocha, tego nikt nie kocha",
"Kto o grosz nie dba, ten grosza nie wart",
"Kto pod kim dołki kopie, sam w nie wpada",
"Kto się lubi, ten się czubi",
"Kto się nie przypomina, o tym zapominają",
"Kto szuka przyjaciela bez wad, pozostanie bez przyjaciela",
"Kto wątpiąc prosi, ten odmawiać uczy",
"Kto z cudzych głupstw nie mędrszy, wiecznie głupim będzie",
"Kto żądze swe hamuje, ten mało potrzebuje",
"Kto żył wesoło, ten żył długo",
"Leniwemu baranowi ciąży jego wełna",
"Lepiej mało a dobrze, niż dużo a źle",
"Lepiej się brzydko ugiąć,, niż ładnie zaszargać",
"Lepiej się na krótko zawstydzić,, niż długo żałować",
"Lepiej z głodu umierać, niż ze wstydu",
"Lepsza prostacka cnota, niż grzeczne występki",
"Lepsza przykrość przed stratą niźli żal po stracie",
"Lepsza swoja chata, niż cudze pałace",
"Lepszy dukat przed procesem, niż trzy po procesie",
"Lepszy jest jawny grzech, niż zmyślona przyjaźń",
"Lepszy mały a częsty zysk, niż duży a rzadki",
"Lepszy swój grosz, niż cudzy trzos",
"Lepszy wróbel w garści, niż gołąb na dachu",
"Licząc cudze pieniądze nikt się nie wzbogaci",
"Lubieżność z cnotą się nie ostoi, mądrość z rozkoszą się nie spoi",
"Ludzie najlepiej nauczą rozumu",
"Ludzi słuchaj, a swój rozum miej",
"Łaska bez datku nie chroni od niedostatku",
"Łatwiej niektórym książkę napisać,, niż drugim ją przeczytać",
"Małe rzeczy zgodą rosną, duże niezgodą upadają",
"Mało się nie sprzykrzy",
"Mądry zawsze się na obydwie strony spodziewa",
"Mądry zachowa majętność i zdrowie, miary potrzeba w sprawach też i w mowie",
"Milczenie bliższe chytrości, niż dobroci",
"Młodości doświadczenia, a starości sił brakuje",
"Młodym robić, mężom rządzić, starym modlić się przystoi",
"Młodzi skwapliwością grzeszą, starzy więcej się czasem lękają,, niż trzeba",
"Mniej to boli, co w oczy nie kole",
"Mowa jest srebrem, a milczenie złotem",
"Muru głową nie przebije, a morza nikt nie wypije",
"Musi to na Rusi, w Polsce jak kto chce",
"Myśl nieśmiertelna nie umie próżnować",
"Myśl o swoimm, zapomnisz o cudzym",
"Na cudzym koniu niedaleko zajedziesz",
"Na nic nauka, kto Boga nie szuka",
"Na nic tam buta, gdzie palce wychodzą z buta",
"Na ostrożności nikt nigdy nie stracił",
"Na pochyłą wierzbę nawet i koza skacze",
"Nadzieja karmi, ale nie tuczy",
"Najlepiej smakuje, co się zapracuje",
"Najlepsza sprawa według starego prawa",
"Najwymowniejszy zazwyczaj ten, kto mówi z przekonania",
"Namierz sprawiedliwie, a przedaj jak możesz",
"Na zamianie zawsze jeden stracić musi",
"Naprzód się nie wyrywaj, na ostatku nie zostaj, środka się zawsze trzymaj",
"Nauka na złe nie radzi",
"Nauka nie rozum, rozum - nie nauka",
"Nauka w głowie, w czynie dzielność, miłość ludzka, skarb nieprzepłacony",
"Nędza wynagradza lenistwo",
"Nic darmo na świecie",
"Nic się na ziemi bez przyczyny nie dzieje",
"Nie było nas, był las; nie będzie nas, będzie las",
"Niech każdy patrzy swego nosa",
"Nie chwaląc nie przedasz, nie ganiać nie kupisz",
"Nie chwal człowieka przed śmiercią",
"Nie dbaj o piękny strój, tylko o pożytek swój",
"Nie jak ludzie mówią, ale jako cnotliwie czynią, na to się zapatruj",
"Nie ma w chlebie ości, kiedy się ciało wypości",
"Nie mów prawdy w oczy, bo kij na cię skoczy",
"Nieobecni nigdy nie mają słuszności",
"Nie pluj w wodę; przyjdzie ci się napić",
"Nie rób drugiemu, co tobie niemiło",
"Nie spodziewałem się tego - jest to słowo człowieka głupiego",
"Nie starość mądrym człeka, ale rozum czyni",
"Nie śmiej się bratku z cudzego upadku",
"Nie to miłe, co miłe, ale to, co się komu podoba",
"Nie tylko w szkole rozumu uczą",
"Nie trzeba człowieka po minie szacować",
"Nie ucz księdza pacierza",
"Nie umiesz się kłaniać, nie przyjdziesz do niczego",
"Niewielka to sztuka być mądrym między głupimi",
"Nie wierz niebu jasnemu, ni człowiekowi śmiejącemu",
"Nie wierz wszystkiemu, co ludzie mówią",
"Nie wstydź się tego, czym jesteś",
"Nie wszystko się dobrze kończy, co się dobrze zaczyna",
"Nie wszystko to bajka, co ludzie bają",
"Nie zmienia się koni w biegu",
"Nie zna obawy, kto pewny swej sprawy",
"Nie życz drugiemu, co tobie niemiło",
"Nowina zła częściej się sprawdzi, niż dobra",
"Obejrz grosz dwa razy, nim go raz wydasz",
"Od miłości do nienawiści jeden krok",
"Od piwa głowa się kiwa",
"Od przybytku głowa nie holi",
"Odzież jest nie dla mody, ale dla wygody",
"Okazja raz stracona rzadko wraca",
"Ostrożnie i wedle miary szafuj słowa i talary",
"Oszczędzaj swego, abyś nie potrzebował cudzego",
"Pamiętaj, człowiecze, że cię niedługo na świecie",
"Pamiętaj rozchodzie, żyj z dochodem w zgodzie",
"Panie gościu! dobrze się sprawuj; cudzego nie bierz, swego nie zostawuj",
"Pańska prośba za rozkazanie stoi",
"Pewnych rzeczy nie odstępuj dla niepewnych",
"Pieniądz rodzi pieniądz",
"Pierwsza miłość od siebie się zaczyna",
"Plotka bawi, pochlebstwo głaszcze, pilność strzeże, rozum bierze",
"Podobać się wszystkim niepodobna",
"Pojednana przyjaźń jak marcowy lód",
"Pokazują oczy, co się w duszy toczy",
"Pośpiech zły doradca",
"Potrzeba czyni człowieka przemyślnym",
"Potrzeba i to czynić każe, czego nie trzeba",
"Powiedz mi, z kim przestajesz, powiem ci, kim jesteś",
"Poznasz w starości, jakim kto był w młodości",
"Póki nie umiesz, poty się ucz",
"Późno nakrywać studnię, gdy już w niej dziecko utonęło",
"Prędka odmowa - datku połowa",
"Prostą drogą cały świat przejdziesz, a krzywą progu nie przestąpisz",
"Przeciwności niesmaczne, ale pożyteczne",
"Przed bitwą nie trąb wygranej",
"Przeszłe przygody bronią od szkody",
"Przez łudzi do chleba, przez świętych do nieba",
"Przygody nauczą zgody",
"Przyjaciół dość nabędziesz, gdy mało brać, wiele dawać będziesz",
"Przyjaźń bez zaufania nic niewarta",
"Przyjaźń szkolna i wojskowa - najtrwalsze",
"Przymuszona modlitwa, przymuszona miłość i przymuszona praca psu na buty", 
"Przysłowie to stare: we wszystkim znaj miarę",
"Przysługa przyjaciół rodzi",
"Przyzwyczajenie jest drugą naturą",
"Rozkosz z początku smakuje, potem katuje",
"Rób co chcesz, a patrz końca",
"Ryby łowią sieciami, ludzi pięknymi słówkami",
"Rzadko rzecz uczciwa bez pożytku bywa",
"Sam się ozwie nie pytany, kto usłyszy swe przygany",
"Siłą posiadł włości, kto ujął chciwości",
"Skoro wąż kogo skaleczy, niechaj go żmija nie leczy",
"Słowo 'moje' i 'twoje' rodzi wszystkie boje",
"Słowo z siłą złote ziarno, a bez siły plewą marną",
"Stara księga, stara prawda i stare wino zawsze dobre",
"Stara miłość nie rdzewieje",
"Starego się trzymaj, kiedy dobre, nowego się imaj, kiedy lepsze",
"Starość nie radość, młodość nie wieczność",
"Strzeż się cichego psa i spokojnej wody",
"Strzelić łatwo, ale trafić trudno",
"Strzeż się pijanego, głupiego i zarażonego",
"Strzeż się takich do domu prosić, co lubią za próg wynosić",
"Suknia wydaje ludzkie obyczaje",
"Swoje zawsze pewniejsze i pożywniejsze, niż cudze",
"Szanujmy mądrych, przykładnych, chwalebnych, śmiejmy się z głupich, choć i przewielebnych",
"Szanuj sam siebie, będą inni ciebie",
"Szata świetna nie ozdobi złego, a podła nie oszpeci dobrego",
"Sztuk, co dobrze nie umiesz, nigdy nie pokazuj",
"Tajemnicę swą wyjawić jest na siebie pęta sprawić",
"Taka jest mowa u ludzi, jakie i życie",
"Ten się nie boi, kto złego nie broi",
"Troski najszczęśliwszemu nieuchronne",
"Trudniej dobrze dzień przeżyć,, niż napisać księgę",
"Ubodzy otwierają bogatym drzwi do raju",
"Ucząc się umieramy",
"Używaj świata, póki śluzą lata",
"W domu powieszonego nie wspominaj o stryczku",
"W głowie skład, w domu ład",
"Widać zwykle z twarzy, co się w sercu waży",
"Wiek długi, majętność ze wczasom, zdrowie dobre, pierwsze po Panu Bogu rzeczy",
"Wielka doskonałość jest umieć pięknie próżnować",
"W miłości i w gniewie co człek czyni, nie wie",
"W przypowieści złe i dobre się mieści",
"W słowach tylko chęć widzim, w działaniu potęgę",
"Wspólne przygody jednają zwykłe zwaśnionych",
"Wstyd jest tarczą cnoty",
"Wstyd panieństwa okrasa",
"Wstyd w młodym człowieku cnota, a w starym - niecnota",
"Wszystko dobre, co się dobrze kończy",
"Wtedyś dobry, kiedy dajesz",
"Wyrzeczonego słowa nie cofniesz do gęby, choćbyś cztery konie zaprzęgnął",
"W zbytnim pośpiechu można ceł przegonić",
"Z Bogiem pokornie, z człowiekiem mężnie, ze szczęściem przezornie poczynaj",
"Z dwojga złego mniejsze obierać trzeba",
"Z każdym bądź grzecznie, a z dobrym serdecznie",
"Z małej iskierki wielkie pożary powstają",
"Z małych przyczyn nieraz wielkie skutki",
"Z młodu nabywaj, na starość używaj",
"Z ogniem i złym człowiekiem żartować nie można",
"Z próżnego i Salomon nie naleje",
"Za dukata brat sprzeda brata", 
"Za młodu żyjesz marzeniami, na starość wspomnieniami",
"Za nic to jest, co umiesz, gdy nikogo nie nauczysz",
"Za szczęścia przyjaciela uczynić, w nieszczęściu doznać",
"Zjesz beczkę soli, nim poznasz do woli",
"Złe dłużej pamiętamy, niż dobre",
"Zostaw Bogu przyszłe rzeczy, dzień dzisiejszy miej na pieczy",
"Zwykle po szkodzie człowiek mądrzejszy",
"Czym głębiej na jesień grzebia się robaki, tym bardziej zimą daje się we znaki",
"Woła wrzesien, że już jesień",
"Gdy nadejdzie wrzesień, wiesniak ma zawsze pelna stodole i kieszen",
"Pazdziernik chodzi po kraju, wygniata ptactwo z gaju",
"Na Szymona i Judy spodziewaj się śniegu i grudy",
"W listopadzie goło w sadzie",
"Kiedy klon wcześnie opada, sroga zimę zapowiada",
"Jesien nie zrodzi czego wiosna nie zasiała",
"W listopadzie mróz, rychtuj w marcu wóz",
"Kiedy Barbara po lodzie, Boże Narodzenie po wodzie",
"Kto rano w Wigilie wstaje, ten przez rok cały nie bedzie ospały",
"Na Gromnice łataj chłopie rekawicę",
"Styczen pogodny wrózy rok płodny",
"W marcu jak w garu",
"W marcu grzmoty, w maju śniegi",
"Gdy dzika gęś w marcu przybywa, ciepła wiosna bywa", 
"Gromniczna pogodna, bedzie jesien dorodna",
"Na świętego Grzegorza, idzie zima do morza",
"Po styczniu jasnym i białym, w lecie bywają upały",
"Kiedy w kwietniu słonko grzeje, tedy chłop nie zubożeje"]

upper = []
lower = []
data.map do |p|
  if p =~ Regexp.new(",")
    parts = p.split(",")
    u = truncate(parts[0].strip, :length => 35, :separator => ' ', :omission => '')
    l = truncate(parts[1].strip, :length => 35, :separator => ' ', :omission => '')
    upper << u unless u.blank?
    lower << l unless l.blank?
  else
    t = truncate(p, :length => 35, :separator => ' ', :omission => '')
    [upper, lower].sample << t unless t.blank?
  end
end

pp upper
pp lower
